// Configuração do Firebase
export const firebaseConfig = {
    apiKey: "AIzaSyAtuwWlErlNOW_c5BlBE_ktwSSmHGLjN2c",
    authDomain: "prototipoos.firebaseapp.com",
    projectId: "prototipoos",
    storageBucket: "prototipoos.firebasestorage.app",
    messagingSenderId: "969276068015",
    appId: "1:969276068015:web:ef7d8c7bfc6f8d5104445a",
    measurementId: "G-85EK8CECR5"
};

// Constantes para controle de dicas
export const TIPS_STATE = {
    WELCOME_TIP: 'welcomeTipClosed',
    QUICK_TIP: 'quickTipClosed',
    MODULES_TIP: 'modulesTipClosed'
};

// Dados de configuração inicial
export const availableEntityIcons = ['user-round', 'file-text', 'package', 'phone', 'building', 'truck', 'dollar-sign', 'tag', 'shopping-cart', 'receipt', 'landmark', 'briefcase'];

export const fieldTypes = [
    { type: 'text', name: 'Texto Curto', icon: 'type' },
    { type: 'textarea', name: 'Texto Longo', icon: 'pilcrow' },
    { type: 'number', name: 'Número', icon: 'hash' },
    { type: 'date', name: 'Data', icon: 'calendar' },
    { type: 'email', name: 'Email', icon: 'at-sign' },
    { type: 'checkbox', name: 'Caixa de Seleção', icon: 'check-square' },
    { type: 'select', name: 'Lista Suspensa', icon: 'chevron-down-square' },
    { type: 'file', name: 'Upload de Ficheiro', icon: 'upload-cloud' },
    { type: 'sub-entity', name: 'Tabela / Relação', icon: 'table-2' },
    // ===== NOVOS TIPOS DE PROPRIEDADE =====
    { type: 'person', name: 'Pessoa', icon: 'user-round', category: 'advanced' },
    { type: 'created-time', name: 'Hora de Criação', icon: 'clock', category: 'system' },
    { type: 'created-by', name: 'Criado por', icon: 'user-plus', category: 'system' },
    { type: 'last-edited-by', name: 'Editado por último', icon: 'user-check', category: 'system' },
    { type: 'button', name: 'Botão', icon: 'play-circle', category: 'automation' },
];

// Configurações padrão para tipos de campos
export const defaultFieldConfigs = {
    text: {
        contentType: 'text',       // text, email, url
        appearance: 'singleLine',  // singleLine, multiLine
        maxLength: null,           // número máximo de caracteres (null = ilimitado)
        required: false            // campo obrigatório
    },
    textarea: {
        contentType: 'text',
        appearance: 'multiLine',
        maxLength: null,
        required: false
    },
    number: {
        format: 'plain',          // plain, thousands, decimal, currency, percentage
        precision: 2,             // número de casas decimais
        symbol: 'R$',             // símbolo de moeda (para formato currency)
        minValue: null,           // valor mínimo (null = ilimitado)
        maxValue: null,           // valor máximo (null = ilimitado)
        required: false
    },
    date: {
        dateFormat: 'DD/MM/AAAA', // DD/MM/AAAA, MM/DD/AAAA, AAAA-MM-DD, complete
        includeTime: 'none',      // none, HH:mm, HH:mm:ss
        behavior: 'singleDate',   // singleDate, dateRange
        defaultValue: 'none',     // none, today
        required: false
    },
    email: {
        contentType: 'email',
        appearance: 'singleLine',
        maxLength: null,
        required: false
    },
    checkbox: {
        defaultValue: false,
        required: false
    },
    select: {
        allowMultiple: false,     // single, multiple
        appearance: 'dropdown',   // dropdown, buttons
        options: [
            { id: 'opt1', label: 'Opção 1' }
        ],
        required: false
    },
    file: {
        allowedTypes: '*',        // mime types ou extensões, * para todos
        maxSize: null,            // tamanho máximo em bytes (null = ilimitado)
        required: false
    },
    'sub-entity': {
        subType: 'independent',   // independent, relationship
        subSchema: { attributes: [] },
        required: false
    },
    // ===== CONFIGURAÇÕES DOS NOVOS TIPOS =====
    person: {
        source: 'workspace',      // workspace, external, custom
        allowMultiple: false,     // permite selecionar múltiplas pessoas
        required: false,
        defaultNotify: false      // notifica a pessoa quando atribuída
    },
    'created-time': {
        format: 'DD/MM/AAAA HH:mm:ss', // formato da data/hora
        includeSeconds: true,     // incluir segundos na visualização
        timezone: 'local',        // local, utc
        readonly: true,           // sempre somente leitura
        autoGenerated: true       // gerado automaticamente pelo sistema
    },
    'created-by': {
        displayFormat: 'name',    // name, email, both
        showAvatar: true,         // mostrar avatar do usuário
        readonly: true,           // sempre somente leitura
        autoGenerated: true       // gerado automaticamente pelo sistema
    },
    'last-edited-by': {
        displayFormat: 'name',    // name, email, both
        showAvatar: true,         // mostrar avatar do usuário
        showTimestamp: true,      // mostrar quando foi editado
        readonly: true,           // sempre somente leitura
        autoGenerated: true       // atualizado automaticamente pelo sistema
    },
    button: {
        label: 'Executar Ação',   // texto do botão
        style: 'primary',         // primary, secondary, success, warning, danger
        size: 'medium',           // small, medium, large
        icon: 'play',             // ícone do botão
        actions: [],              // array de ações a serem executadas
        confirmBeforeExecute: false, // pedir confirmação antes de executar
        confirmMessage: 'Tem certeza que deseja executar esta ação?',
        successMessage: 'Ação executada com sucesso!',
        showProgressIndicator: true // mostrar indicador de progresso durante execução
    }
};